# Generated by Django 4.0.6 on 2022-07-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_author_slug_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='mainapp.category'),
            preserve_default=False,
        ),
    ]
