# Generated by Django 4.0.6 on 2022-07-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('mainapp', '0002_alter_bookreview_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_book_reviews', to='authapp.customer'),
        ),
    ]
