# Generated by Django 4.0.6 on 2022-07-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_author_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
