# Generated by Django 4.0.6 on 2022-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='https://dummyimage.com/600x400/000/fff', upload_to=''),
            preserve_default=False,
        ),
    ]
