# Generated by Django 4.0.6 on 2022-07-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_customer_user_delete_profile'),
        ('mainapp', '0007_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authapp.customer')),
            ],
        ),
    ]
