# Generated by Django 4.0.6 on 2022-07-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_author_category'),
        ('cartapp', '0002_remove_cart_product_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_products', to='cartapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='mainapp.book')),
            ],
        ),
        migrations.DeleteModel(
            name='CartBookOrder',
        ),
    ]
